// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn_uaF_eWaUlhgffx88fhhwvgaVj-yBL4',
    appId: '1:799022853031:web:db28a6ad51906f8ce8e482',
    messagingSenderId: '799022853031',
    projectId: 'vote-d1ae4',
    authDomain: 'vote-d1ae4.firebaseapp.com',
    storageBucket: 'vote-d1ae4.firebasestorage.app',
    measurementId: 'G-ZSS751SMED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJj10XdThIZUIH_jXz79FN5dygom1dtE4',
    appId: '1:799022853031:android:4f87536d67a463b9e8e482',
    messagingSenderId: '799022853031',
    projectId: 'vote-d1ae4',
    storageBucket: 'vote-d1ae4.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBljxGLXMfeZjbZRbmqJPFzHOMTEV35Cg',
    appId: '1:799022853031:ios:bd66dbad37d10affe8e482',
    messagingSenderId: '799022853031',
    projectId: 'vote-d1ae4',
    storageBucket: 'vote-d1ae4.firebasestorage.app',
    iosBundleId: 'com.secureevoting.secureEVoting',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBljxGLXMfeZjbZRbmqJPFzHOMTEV35Cg',
    appId: '1:799022853031:ios:bd66dbad37d10affe8e482',
    messagingSenderId: '799022853031',
    projectId: 'vote-d1ae4',
    storageBucket: 'vote-d1ae4.firebasestorage.app',
    iosBundleId: 'com.secureevoting.secureEVoting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn_uaF_eWaUlhgffx88fhhwvgaVj-yBL4',
    appId: '1:799022853031:web:6c559128016b68d6e8e482',
    messagingSenderId: '799022853031',
    projectId: 'vote-d1ae4',
    authDomain: 'vote-d1ae4.firebaseapp.com',
    storageBucket: 'vote-d1ae4.firebasestorage.app',
    measurementId: 'G-LE684ZW3MB',
  );
}
