// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALxPYequ5-mGJaCcwh9rGkXaEEw9kqcF4',
    appId: '1:1045202096686:web:8b76d772ec45c3cb9205bf',
    messagingSenderId: '1045202096686',
    projectId: 'e-voteing-system',
    authDomain: 'e-voteing-system.firebaseapp.com',
    storageBucket: 'e-voteing-system.firebasestorage.app',
    measurementId: 'G-6S4YWVN40J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2qhQCVID81_wkiHEiUYHa3Ln144zmJpQ',
    appId: '1:1045202096686:android:0199f5cd9923d3e89205bf',
    messagingSenderId: '1045202096686',
    projectId: 'e-voteing-system',
    storageBucket: 'e-voteing-system.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBph-Eesstvywv69F-I7NfAV1hGzfp7iO8',
    appId: '1:1045202096686:ios:ec18e70349ffa8869205bf',
    messagingSenderId: '1045202096686',
    projectId: 'e-voteing-system',
    storageBucket: 'e-voteing-system.firebasestorage.app',
    iosClientId: '1045202096686-m0p2b6ssqr0b09ur9edsjqjfmcttubov.apps.googleusercontent.com',
    iosBundleId: 'com.secureevoting.secureEVoting',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN0ghUOtFKKu3iUwUDNhlPWuhpIvP5zug',
    appId: '1:591897856413:ios:47045893681e0e23974774',
    messagingSenderId: '591897856413',
    projectId: 'e-voting-system-a44d6',
    storageBucket: 'e-voting-system-a44d6.firebasestorage.app',
    iosClientId: '591897856413-2a4lgflgug3v67qqum6uvnsa9b3qloee.apps.googleusercontent.com',
    iosBundleId: 'com.secureevoting.secureEVoting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwfvqSD4daZK_9CHJQYJRpuZWDkL0SvI4',
    appId: '1:591897856413:web:6c2db3014170f6ee974774',
    messagingSenderId: '591897856413',
    projectId: 'e-voting-system-a44d6',
    authDomain: 'e-voting-system-a44d6.firebaseapp.com',
    storageBucket: 'e-voting-system-a44d6.firebasestorage.app',
    measurementId: 'G-S70ZCTRPYX',
  );
}
